### ISSUE TITLE
Создать таблицу для хранения прайс - листов

### ISSUE THREAD

**Issue by AVM82** [team2soft/provisor2#10]
Создать таблицу для хранения прайс - листов. 
Назвать _AC_PRICE, поля в соответствии с файлами от поставщиков 
product_name | purchase_price | builder_name | code | bar_code | series | shelf life | nds

**Comment by roman1bondarenko** [comment]
CREATE TABLE [dbo].[_AC_PRICE](
 [ENTERPRISE_ID] [nchar](25) NOT NULL,
  [GOODS_ID] [nvarchar](25) NOT NULL, 
 [GOODS_NAME] [nvarchar](150) NOT NULL,
 [BUILDER_NAME] [nvarchar](150) NULL,
 [PRICE] [numeric](12, 2) NOT NULL,
 [EXPDATE] [nvarchar](12) NULL,
 [MORION_ID] [numeric](18, 0) NULL,
  [ZAVOD] [nvarchar](50) NULL, 
 [NDS] [numeric](2, 0) NOT NULL,
 [SERIES] [nvarchar](25) NULL)
